In [31]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

from sklearn import datasets
import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')


In [32]:
# In[2]:


wine=pd.read_csv("wine.csv")



In [33]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
X=wine.iloc[:,:-1].values
y=wine.iloc[:,-1].values


Xtrain, Xtest, y_train, y_test = train_test_split(X, y)
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)


In [34]:
r2_score(y_pred, y_test)

0.4705241502672505

In [35]:
# fitting the LDA model
lda = LDA(n_components=2)
lda_X = lda.fit(X,y).transform(X)




In [36]:
lda_X

array([[-2.48030082,  1.12569575],
       [-1.01769838,  1.69763388],
       [-1.39436453,  1.42234636],
       [-4.68945363, -0.14222092],
       [-2.28703286, -1.41944752],
       [-2.76911208,  1.61852269],
       [-2.99469069,  0.92335527],
       [-2.89259635, -0.40150504],
       [-3.48721173,  1.2180737 ],
       [-2.91743455,  1.5329405 ],
       [-2.25393327,  2.59875623],
       [-2.79035593,  1.00967585],
       [-2.16663697,  1.8854697 ],
       [-1.42791545,  4.71327891],
       [-1.68762873,  5.31719126],
       [-1.72892239,  3.18431207],
       [-3.33038136,  0.06013974],
       [-2.31857908,  0.83197348],
       [-1.82468561,  4.37000141],
       [-1.97417697,  0.82854081],
       [-2.58049708,  1.14435959],
       [-0.97757357,  0.59435589],
       [-1.9992344 ,  0.48625582],
       [-1.93651842, -0.33358351],
       [-2.65119943, -0.83905355],
       [-2.17879191, -2.31148438],
       [-2.52021474, -0.63288056],
       [-2.72172593, -1.19743561],
       [-2.42065601,

In [37]:
# Importing Libraries for Modelling.
from sklearn import  datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


# In[20]:





In [38]:
X

array([[ 1.  , 14.23,  1.71, ...,  5.64,  1.04,  3.92],
       [ 1.  , 13.2 ,  1.78, ...,  4.38,  1.05,  3.4 ],
       [ 1.  , 13.16,  2.36, ...,  5.68,  1.03,  3.17],
       ...,
       [ 3.  , 13.27,  4.28, ..., 10.2 ,  0.59,  1.56],
       [ 3.  , 13.17,  2.59, ...,  9.3 ,  0.6 ,  1.62],
       [ 3.  , 14.13,  4.1 , ...,  9.2 ,  0.61,  1.6 ]])

In [39]:
# Assigning values of X and y from dataset


X=wine.iloc[:,:-1].values
y=wine.iloc[:,-1].values




In [40]:
X

array([[ 1.  , 14.23,  1.71, ...,  5.64,  1.04,  3.92],
       [ 1.  , 13.2 ,  1.78, ...,  4.38,  1.05,  3.4 ],
       [ 1.  , 13.16,  2.36, ...,  5.68,  1.03,  3.17],
       ...,
       [ 3.  , 13.27,  4.28, ..., 10.2 ,  0.59,  1.56],
       [ 3.  , 13.17,  2.59, ...,  9.3 ,  0.6 ,  1.62],
       [ 3.  , 14.13,  4.1 , ...,  9.2 ,  0.61,  1.6 ]])

In [41]:
y

array([1065, 1050, 1185, 1480,  735, 1450, 1290, 1295, 1045, 1045, 1510,
       1280, 1320, 1150, 1547, 1310, 1280, 1130, 1680,  845,  780,  770,
       1035, 1015,  845,  830, 1195, 1285,  915, 1035, 1285, 1515,  990,
       1235, 1095,  920,  880, 1105, 1020,  760,  795, 1035, 1095,  680,
        885, 1080, 1065,  985, 1060, 1260, 1150, 1265, 1190, 1375, 1060,
       1120,  970, 1270, 1285,  520,  680,  450,  630,  420,  355,  678,
        502,  510,  750,  718,  870,  410,  472,  985,  886,  428,  392,
        500,  750,  463,  278,  714,  630,  515,  520,  450,  495,  562,
        680,  625,  480,  450,  495,  290,  345,  937,  625,  428,  660,
        406,  710,  562,  438,  415,  672,  315,  510,  488,  312,  680,
        562,  325,  607,  434,  385,  407,  495,  345,  372,  564,  625,
        465,  365,  380,  380,  378,  352,  466,  342,  580,  630,  530,
        560,  600,  650,  695,  720,  515,  580,  590,  600,  780,  520,
        550,  855,  830,  415,  625,  650,  550,  5

In [42]:
#Setting training and testing values

Xtrain, Xtest, y_train, y_test = train_test_split(X, y)
scaler = preprocessing.StandardScaler().fit(Xtrain)
Xtrain = scaler.transform(Xtrain)
Xtest = scaler.transform(Xtest)

In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(Xtrain,y_train)
y_pred = classifier.predict(Xtest)


In [44]:
from sklearn.metrics import r2_score

In [45]:
r2_score(y_pred,y_test)

0.5445650979720407