In [ ]:
import numpy as np

In [ ]:
a_arr=np.random.randint(low=10,high=90,size=(4,5))

In [ ]:
a_arr

array([[57, 63, 58, 40, 33],
       [14, 80, 57, 22, 30],
       [66, 18, 30, 10, 69],
       [13, 53, 30, 27, 24]])

In [ ]:
a_arr[1,4:1:-1]

array([30, 22, 57])

In [ ]:
a_arr[-3,-1:-4:-1]

array([30, 22, 57])

In [ ]:
#filtering
#syntax
#np.where(condition,what_to_do_if_true,what_to_do_if_false)
b_arr=np.random.randint(10,90,12)

In [ ]:
b_arr

array([13, 75, 54, 24, 49, 45, 82, 51, 28, 67, 89, 62])

In [ ]:
np.where(b_arr>80)

(array([ 6, 10]),)

In [ ]:
np.where(b_arr>80,b_arr,0)

array([ 0,  0,  0,  0,  0,  0, 82,  0,  0,  0, 89,  0])