In [ ]:
# NumPy - maths in python
# Pandas - read,edit data in python (data manipulation)
# matplotlib (data visualization)

# All these are third party libraries

# install package
# ! pip install numpy

#to check if numpy isinstall or not
# pip show numpy

In [ ]:
! pip show numpy

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbprophet, fastprog

In [ ]:
#to uninstall any package
# ! pip uninstall numpy

#to upgrade
# ! pip install --upgrade numpy

In [ ]:
# to check list of all packages installed
! pip list

Package                       Version
----------------------------- --------------
absl-py                       0.12.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.1.0
appdirs                       1.4.4
argcomplete                   1.12.3
argon2-cffi                   21.1.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.2.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.2
branca                        0.4.2
bs4                           0.0.1
CacheControl

In [ ]:
alist=[1,2,3,4,5]
#to multiply by 2
alist1=2*[1,2,3,4,5] # won't work

In [ ]:
print(alist1)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
blist=[]
for item in alist:
  blist.append(2*item)

In [ ]:
blist

[2, 4, 6, 8, 10]

In [ ]:
# base python lacks two things
#1. loops are bad in computation
#2. dimentionality - base pythin datatypes like list,tuple cannot understand 2D data(rows,column)

In [ ]:
# this problem is solved by numpy
#Numpy ---> datatype array
#1. Arrays are multi dimentional
#2.Numpy broadcasting

In [ ]:
import numpy as np

In [ ]:
# how to convert a list as array
print(alist)
a_arr=np.array(alist)
print(a_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
type(alist)



list

In [ ]:
type(a_arr) # nth dimentional array

numpy.ndarray

In [ ]:
a_arr*2

array([ 2,  4,  6,  8, 10])

In [ ]:
b_arr=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
b_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b_arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#how to make an array with ZEROs
#always pass your shape in tuple (rows,columns)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
c_arr=np.zeros((3,5),dtype=int)

In [ ]:
c_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
d_arr=np.ones((3,4),dtype=int)

In [ ]:
e_arr=d_arr*7

In [ ]:
e_arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
# generate random numbers from numpy
np.random.randint(low=10, high=90, size=(3,4))

array([[23, 51, 65, 82],
       [76, 25, 77, 56],
       [18, 38, 13, 11]])

In [ ]:
e_arr.shape # rows,columns

(3, 4)

In [ ]:
e_arr.size

12

In [ ]:
e_arr.max()

7

In [ ]:
e_arr.min()

7

In [ ]:
e_arr.mean()

7.0

In [ ]:
f_arr=np.random.randint(low=20,high=90,size=(3,4))

In [ ]:
f_arr

array([[44, 63, 52, 26],
       [68, 20, 69, 82],
       [75, 37, 54, 63]])

In [ ]:
f_arr.max(axis=1) # across each row what is the maximum

array([63, 82, 75])

In [ ]:
f_arr.max(axis=0) #max valu acreoss each column

array([75, 63, 69, 82])

In [ ]:
f_arr.sum(axis=1)

array([185, 239, 229])

In [ ]:
f_arr.sum(axis=0)

array([187, 120, 175, 171])

In [ ]:
f_arr

array([[44, 63, 52, 26],
       [68, 20, 69, 82],
       [75, 37, 54, 63]])

In [ ]:
f_arr.sum(axis=1)[2]


229

In [ ]:
#golden rule in python
# always start from Zero whenever counting in python
# whenever you are calculation the range ,the last limit is exclusive

In [ ]:
#slicing & indexing
#indexing
#syntax arr_name[row_num,col_num]

In [ ]:
f_arr

array([[44, 63, 52, 26],
       [68, 20, 69, 82],
       [75, 37, 54, 63]])

In [ ]:
f_arr[1,3]

82

In [ ]:
#slicing
# syntax arr_name[row_start_num:row_stop_num,col_start_num:col_end_num]

In [ ]:
f_arr

NameError: ignored

In [ ]:
f_arr[1:3,2:4]

array([[69, 82],
       [54, 63]])

In [ ]:
# steppings in array