In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import FactorAnalysis as FA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
df = pd.read_csv('iris.data')

In [ ]:
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [ ]:
df.columns=['sepal_length','sepal_width','petal_length','petal_width','class']

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [ ]:
x = df.iloc[:,:4]
y=df.iloc[:,4:]

In [ ]:
x.head()


sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

In [ ]:
y.head()

class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
sc= StandardScaler()


In [ ]:
X_train= sc.fit_transform(x_train)
X_test = sc.transform(x_test)

Create a RandomForestCLassifier train it on scaled data and print its accuracy score and confusion matrix.

In [ ]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
ypred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [ ]:
CM = confusion_matrix(y_test,ypred)
print(CM)
print('Accuracy score: ',accuracy_score(y_test,ypred))

[[16  0  0]
 [ 0 15  1]
 [ 0  4  9]]
Accuracy score:  0.8888888888888888


Create FactorAnalysis or FA instance and transform x_train and x_test.

In [ ]:
fa = FA(n_components=1)
Xtrain_fa = fa.fit_transform(X_train)
Xtest_fa =fa.transform(X_test)

Create a RandomForestCLassifier train it on scaled and transformed data and print its accuracy score and confusion matrix.

In [ ]:
fa_model = RandomForestClassifier(max_depth=2,random_state=0)
fa_model.fit(Xtrain_fa,y_train)
ypred = fa_model.predict(Xtest_fa)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [ ]:
CM = confusion_matrix(y_test,ypred)
print(CM)
print('Accuracy score: ',accuracy_score(y_test,ypred))

[[16  0  0]
 [ 0 14  2]
 [ 0  1 12]]
Accuracy score:  0.9333333333333333


Define a function called perform_fa that takes number of components for PCA to find and creates a RandomForestClassifier and calculates its accuracy.

In [ ]:
def perform_fa(n):
  xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=0)
  sc = StandardScaler()
  Xtrain = sc.fit_transform(xtrain)
  Xtest = sc.transform(xtest)
  fa = FA(n_components=n)
  fa_xtrain = fa.fit_transform(Xtrain)
  fa_xtest = fa.transform(Xtest)
  classifier = RandomForestClassifier(max_depth=2,random_state=0)
  classifier.fit(fa_xtrain,ytrain)
  y_pred=classifier.predict(fa_xtest)
  cm = confusion_matrix(ytest,y_pred)
  print(cm)
  print('accuracy score: ',accuracy_score(ytest,y_pred))

  



Call the perform_lda method with n_components set to a number from 1 to 4 and print their confusion matrix and accuracy scores.

In [ ]:
for i in range(1,5):
  perform_fa(i)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[16  0  0]
 [ 0 14  2]
 [ 0  1 12]]
accuracy score:  0.9333333333333333


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[16  0  0]
 [ 0 14  2]
 [ 0  1 12]]
accuracy score:  0.9333333333333333


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[15  1  0]
 [ 0 13  3]
 [ 0  4  9]]
accuracy score:  0.8222222222222222


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[16  0  0]
 [ 0 14  2]
 [ 0  2 11]]
accuracy score:  0.9111111111111111
