In [38]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [39]:
df = pd.read_csv('iris.data')

In [40]:
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [41]:
df.columns=['sepal_length','sepal_width','petal_length','petal_width','class']

In [42]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [43]:
x = df.iloc[:,:4]
y=df.iloc[:,4:]

In [44]:
x.head()


sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

In [45]:
y.head()

class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [46]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [47]:
sc= StandardScaler()


In [48]:
X_train= sc.fit_transform(x_train)
X_test = sc.transform(x_test)

Create a RandomForestCLassifier train it on scaled data and print its accuracy score and confusion matrix.

In [49]:
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train,y_train)
ypred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [50]:
CM = confusion_matrix(y_test,ypred)
print(CM)
print('Accuracy score: ',accuracy_score(y_test,ypred))

[[16  0  0]
 [ 0 15  1]
 [ 0  4  9]]
Accuracy score:  0.8888888888888888


Create n LDA instance and transform x_train and x_test.

In [52]:
lda = LDA(n_components=1)
Xtrain_lda = lda.fit_transform(X_train,y_train)
Xtest_lda =lda.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Create a RandomForestCLassifier train it on scaled and transformed data and print its accuracy score and confusion matrix.

In [53]:
lda_model = RandomForestClassifier(max_depth=2,random_state=0)
lda_model.fit(Xtrain_lda,y_train)
ypred = lda_model.predict(Xtest_lda)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [54]:
CM = confusion_matrix(y_test,ypred)
print(CM)
print('Accuracy score: ',accuracy_score(y_test,ypred))

[[16  0  0]
 [ 0 16  0]
 [ 0  1 12]]
Accuracy score:  0.9777777777777777


Define a function called perform_lda that takes number of components for PCA to find and creates a RandomForestClassifier and calculates its accuracy.

In [56]:
def perform_lda(n):
  xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=0)
  sc = StandardScaler()
  Xtrain = sc.fit_transform(xtrain)
  Xtest = sc.transform(xtest)
  lda = LDA(n_components=n)
  lda_xtrain = lda.fit_transform(Xtrain,ytrain)
  lda_xtest = lda.transform(Xtest)
  classifier = RandomForestClassifier(max_depth=2,random_state=0)
  classifier.fit(lda_xtrain,ytrain)
  y_pred=classifier.predict(lda_xtest)
  cm = confusion_matrix(ytest,y_pred)
  print(cm)
  print('accuracy score: ',accuracy_score(ytest,y_pred))

  



Call the perform_ldaa method with n_components set to a number from 1 to 4 and print their confusion matrix and accuracy scores.

In [58]:
for i in range(1,3):
  perform_lda(i)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example

[[16  0  0]
 [ 0 16  0]
 [ 0  1 12]]
accuracy score:  0.9777777777777777
[[16  0  0]
 [ 0 16  0]
 [ 0  3 10]]
accuracy score:  0.9333333333333333
