In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

In [2]:
df = pd.read_csv('iris.data')

In [3]:
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [4]:
df.columns=['sepal_length','sepal_width','petal_length','petal_width','class']

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [9]:
x = df.iloc[:,:4]
y=df.iloc[:,4:]

In [10]:
x.head()


sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

In [11]:
y.head()

class
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa
4  Iris-setosa

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [14]:
sc= StandardScaler()


In [15]:
X_train= sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [16]:
pca = PCA()
Xtrain_PCA = pca.fit_transform(X_train)
Xtest_PCA =pca.transform(X_test)

In [17]:
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.73982698, 0.21684733, 0.03908888, 0.00423682])

Define a function called perform_pca that takes number of components for PCA to find and creates a RandomForestClassifier and calculates its accuracy.

In [21]:
def perform_pca(n):
  xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=0)
  sc = StandardScaler()
  Xtrain = sc.fit_transform(xtrain)
  Xtest = sc.transform(xtest)
  pca = PCA(n_components=n)
  pca_xtrain = pca.fit_transform(Xtrain)
  pca_xtest = pca.transform(Xtest)
  classifier = RandomForestClassifier(max_depth=2,random_state=0)
  classifier.fit(pca_xtrain,ytrain)
  y_pred=classifier.predict(pca_xtest)
  cm = confusion_matrix(ytest,y_pred)
  print(cm)
  print('accuracy score: ',accuracy_score(ytest,y_pred))

  



Call the perform_pca method with n_components set to a number from 1 to 4 and print their confusion matrix and accuracy scores.

In [23]:
for i in range(1,5): perform_pca(i)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[16  0  0]
 [ 0 15  1]
 [ 0  2 11]]
accuracy score:  0.9333333333333333
[[16  0  0]
 [ 0 12  4]
 [ 0  4  9]]
accuracy score:  0.8222222222222222


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


[[16  0  0]
 [ 0 12  4]
 [ 0  4  9]]
accuracy score:  0.8222222222222222
[[16  0  0]
 [ 0 13  3]
 [ 0  4  9]]
accuracy score:  0.8444444444444444
