In [ ]:
Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True,
8.10
a. Now in the ‘myList’, append these values: 30,40
b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [1]:
import numpy as np

In [2]:
myList = np.array([10,20,30,'apple',True,8.10])

In [3]:
print(myList)

['10' '20' '30' 'apple' 'True' '8.1']


In [8]:
myList = np.concatenate((myList,[30,40]))

In [9]:
#After that reverse the elements of the ‘myList’ and store that in ‘reversedList’

In [10]:
reversedList = myList[::-1]
print(reversedList)

['40' '30' '8.1' 'True' 'apple' '30' '20' '10']


In [11]:
newreversedList = np.flipud(myList)
print(newreversedList)

['40' '30' '8.1' 'True' 'apple' '30' '20' '10']


2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
a. After that eliminate the ‘text’ value form the dictonary.
b. Add ‘features’ in the dictonary.
c. Fetch the ‘data’ element from the dictonary and display it in the output.

In [12]:
#Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
dict1 = {1:'data',2:'information',3:'text'}
print(dict1)

{1: 'data', 2: 'information', 3: 'text'}


In [14]:
#After that eliminate the ‘text’ value form the dictonary
dict1.pop(3)

'text'

In [15]:
print(dict1)

{1: 'data', 2: 'information'}


In [16]:
dict1[3] = 'Features'

In [17]:
print(dict1)

{1: 'data', 2: 'information', 3: 'Features'}


In [18]:
 #Fetch the ‘data’ element from the dictonary and display it in the output

In [20]:
dict1[1]

'data'

In [21]:
#3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple

In [22]:
my_tuple = 1,2,3,'apple','mango'
print(my_tuple)

(1, 2, 3, 'apple', 'mango')


 4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50
a. Find the minimum value from the numeric_tuple.
b. Concatenate my_tuple with numeric_tuple and store the result in r1.
c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [23]:
 #Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50

In [24]:
numeric_tuple = ((10,20,30,40,50,))

In [25]:
print(numeric_tuple)

(10, 20, 30, 40, 50)


In [26]:
#Find the minimum value from the numeric_tuple

In [27]:
np.min(numeric_tuple)

10

In [28]:
#Concatenate my_tuple with numeric_tuple and store the result in r1.

In [29]:
r1 = my_tuple + numeric_tuple
print(r1)

(1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)


In [30]:
r1 = np.concatenate((numeric_tuple,my_tuple))

In [31]:
print(r1)

['10' '20' '30' '40' '50' '1' '2' '3' 'apple' 'mango']


In [32]:
#c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.

In [34]:
#newdupli = my_tuple *2
newdupli = my_tuple + my_tuple
print(newdupli)

(1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to
contains{2,3,7,6,1}
a. Perform the below operation:
a. set1 union set2
b. set1 intersection set2
c. set1 difference set2

In [ ]:
Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to
contains{2,3,7,6,1}

In [35]:
set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}

In [ ]:
# set1 union set2

In [39]:
#print(set1 | set2)
print(set1.union(set2))

{1, 2, 3, 4, 5, 6, 7}


In [40]:
#set1 intersection set2

In [41]:
print(set1.intersection(set2))

{1, 2, 3}


In [42]:
#set1 difference set2

In [43]:
print(set1.difference(set2))

{4, 5}


In [45]:
#Assignment 2

In [46]:
#1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [48]:
ar1 = np.random.randint(2,11,(3,3))
print(ar1)

[[5 8 2]
 [8 5 9]
 [5 9 6]]


In [50]:
ar2 = np.arange(2,11).reshape(3,3)
print(ar2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
2. Create a numpy array having user input values and convert the integer type to the float type
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [55]:
x = int(input())
arr = np.arange(x,dtype = float)
arr

5


array([0., 1., 2., 3., 4.])

In [ ]:
3. Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [61]:
arr_one = np.arange(10,31,10)
arr_two = np.arange(40,91,10)
#np.concatenate((arr_one,arr_two))
np.append(arr_one,arr_two)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
4. Create two numpy arrays and add the elements of both the arrays and store the result in
sumArray

In [64]:
ar1 = np.arange(10,91,10).reshape(3,3)
ar2 = np.arange(20,101,10).reshape(3,3)
#sumArray = ar1+ar2
sumArray = np.sum(ar1) + np.sum(ar2)

In [65]:
sumArray

990

In [ ]:
5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array.

In [66]:
array1 = np.arange(10,91,10).reshape(3,3)
array1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [67]:
array1[0:1]

array([[10, 20, 30]])

In [69]:
array1[0,0:]

array([10, 20, 30])

In [70]:
array1[0]

array([10, 20, 30])

In [72]:
array1[0,2]

30

In [74]:
array1[0]

array([10, 20, 30])

In [75]:
array_one = np.arange(10,91, 10).reshape(3,3)
#for first row
array_5 = array_one[0,:]
print("First Row:",array_5)

#for last element
array_6 = array_one[-1,-1]
print("East Element:",array_6)


First Row: [10 20 30]
East Element: 90


In [76]:
array1[2,2]

90

In [77]:
array1[-1,-1]

90

In [78]:
array1[2:,-1:]

array([[90]])