1. Create a 3x3 matrix array with values ranging from 2 to 10

In [1]:
import numpy as np

In [6]:
A1=np.random.randint(2,10,(3,3))
print(A1)

[[8 7 4]
 [4 3 4]
 [3 5 9]]


2. Create a numpy array having user input values and convert the integer type to the float type 
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]


In [21]:
A2=int(input())
np.arange(A2,dtype=float)


5


array([0., 1., 2., 3., 4.])

3.Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [31]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60,70,80,90])
arr3=np.append(arr1,arr2)
print(arr3)

[10 20 30 40 50 60 70 80 90]


4.Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.


In [40]:
#Add colums of two arrays
B1=np.array([10,20,30,80])
B2=np.array([40,80,20,50])
sumArray=np.add(B1,B2)
print(sumArray)

[ 50 100  50 130]


In [41]:
#add sum of two arrays
C1=np.array([10,20,30,80])
C2=np.array([40,80,20,50])
sumArray1=np.sum(C1)+np.sum(C2)
print(sumArray1)

330


5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array.

In [43]:
array1=np.arange(10,100,10).reshape(3,3)
print(array1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [47]:
array1[0:1]

array([[10, 20, 30]])

In [49]:
array1[2:,2:]


array([[90]])

In [50]:
array1[2,2]

90

In [52]:
array1[-1,-1]

90