1.Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a 
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]


In [1]:
import numpy as np

In [2]:
A=[(3,3),5]
print(A)

B=A[0]
print(B)

C=A[1]
print(C)

def array(x,y):
  arr=np.ones(x,dtype=int)*y
  return arr
  #print(arr)

array(B,C)

[(3, 3), 5]
(3, 3)
5


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

2. Create a method that takes n Numpy arrays of same dimensions sums them and return the 
answer

In [14]:
A1=np.random.randint(1,10,(4,4))
print(A1)
A2=np.random.randint(10,20,(4,4))
print(A2)
A3=np.random.randint(20,30,(4,4))
print(A3)

def arrSum(A1,A2,A3):
  A4 = A1+A2+A3
  return A4

arrSum(A1,A2,A3)

[[4 7 4 5]
 [3 1 3 7]
 [5 7 8 3]
 [4 6 2 7]]
[[11 11 12 16]
 [12 18 17 15]
 [18 16 10 13]
 [11 15 14 11]]
[[23 21 20 29]
 [24 27 20 27]
 [29 21 21 20]
 [20 26 27 24]]


array([[38, 39, 36, 50],
       [39, 46, 40, 49],
       [52, 44, 39, 36],
       [35, 47, 43, 42]])

3.Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]


In [6]:
N=int(input("please enter num of rows:"))
M=int(input("please enter num of columns:"))

arr=np.random.randint(1,10,(N,M))
print(arr)

def subMat(arr,N,M):
  sub_matrix=arr[:N-1,:M-1]
  return sub_matrix

subMat(arr,N,M)

please enter num of rows:3
please enter num of columns:3
[[5 3 6]
 [1 7 4]
 [4 8 9]]


array([[5, 3],
       [1, 7]])

4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two 
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]

In [11]:
N=int(input("please enter num of rows:"))
M=int(input("please enter num of columns:"))

arr=np.random.randint(1,10,(N,M))
print(arr)

def subMat(arr,N,M):
  sub_matrix=arr[-N+1:,-M+1:]
  return sub_matrix

subMat(arr,N,M)

please enter num of rows:4
please enter num of columns:5
[[4 3 7 8 9]
 [3 2 9 7 8]
 [8 5 3 8 2]
 [4 3 5 6 4]]


array([[2, 9, 7, 8],
       [5, 3, 8, 2],
       [3, 5, 6, 4]])

 5.Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method 
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's 
standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}

In [13]:
arr=[2,4,6,8,10]
dict1={}
def dict(arr):
  avg=np.mean(arr)
  dict1["mean"]=avg
  print(dict1)

  dev=np.std(arr)
  dict1["std_dev"]=dev
  print(dict1)

dict(arr)

{'mean': 6.0}
{'mean': 6.0, 'std_dev': 2.8284271247461903}
