In [ ]:
# Numpy         Maths in Python 
# Pandas        Read, Edit the data 
# Matplotlib    Viz the data

In [ ]:
# 3rd party library/ packages 

In [ ]:
# str, int, float, dict, set - base python

In [ ]:
# Download, Install & Import in our project

In [ ]:
# Install numpy package
#! pip install numpy

In [ ]:
# Check if numpy is installed or not ? 
! pip show numpy

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbprophet, fastprog

In [ ]:
# Uninstall numpy
# ! pip uninstall numpy 

# Upgrade numpy package 
# ! pip install --upgrade numpy

In [ ]:
# List of all the python packages installed
! pip list

In [ ]:
alist = [1,2,3,4,5]
# multiply each element by 2
# output = [2,4,6,8,10]

In [ ]:
alist * 2 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
blist = []
for item in alist: 
  blist.append(item*2)
blist 

[2, 4, 6, 8, 10]

In [ ]:
(1_000_000 / 3600)/24

11.574074074074074

In [ ]:
# Base Python lacks 2 things - 
# 1. Loop are bad in terms of computation 
# 2. Dimentionality - base python data types (list, tuple & dict) cant understand 2D data (row & columns)

In [ ]:
# Numpy - data type array -> 
# 1. Array are multi dimentional in nature
# 2. Numpy broadcasting . . . .  

In [ ]:
import numpy as np

In [ ]:
# how to convert a list into an array 
print(alist)
a_arr = np.array(alist)
a_arr

[1, 2, 3, 4, 5]


array([1, 2, 3, 4, 5])

In [ ]:
type(alist)

list

In [ ]:
type(a_arr) #ndarray - nth dimentional array

numpy.ndarray

In [ ]:
a_arr

array([1, 2, 3, 4, 5])

In [ ]:
a_arr * 2 

array([ 2,  4,  6,  8, 10])

In [ ]:
b_arr = np.array([[1,2,3],
                  [3,2,1],
                  [9,8,7]])
b_arr

array([[1, 2, 3],
       [3, 2, 1],
       [9, 8, 7]])

In [ ]:
b_arr * 2

array([[ 2,  4,  6],
       [ 6,  4,  2],
       [18, 16, 14]])

In [ ]:
# How to make an array with ZERO's! 

# Always pass your shape in a tuple (row, column)
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((5,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
c_arr = np.zeros((5,3), dtype=int)

In [ ]:
c_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
# Make an array with 3 rows and 5 columns and filled with 7

In [ ]:
# only np.ones and np.zeros 
np.zeros((3,5)) + 7 

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [ ]:
# generate random numbers from numpy

np.random.randint(low=10, high=90, size=(4,5))

array([[35, 22, 88, 70, 22],
       [25, 75, 25, 15, 65],
       [72, 42, 53, 20, 32],
       [34, 63, 76, 46, 24]])

In [ ]:
d_arr = np.random.randint(low=10, high=90, size=(4,5))

In [ ]:
d_arr.shape # rows, columns

(4, 5)

In [ ]:
d_arr.size

20

In [ ]:
d_arr

array([[37, 28, 41, 33, 43],
       [63, 70, 25, 66, 49],
       [43, 19, 15, 74, 76],
       [34, 36, 65, 60, 11]])

In [ ]:
d_arr.max()

76

In [ ]:
d_arr.min()

11

In [ ]:
d_arr.sum()

888

In [ ]:
d_arr.mean()

44.4

In [ ]:
# Operations across axis

In [ ]:
d_arr

array([[37, 28, 41, 33, 43],
       [63, 70, 25, 66, 49],
       [43, 19, 15, 74, 76],
       [34, 36, 65, 60, 11]])

In [ ]:
d_arr.max(axis=1) # across each row what is the max number

array([43, 70, 76, 65])

In [ ]:
d_arr.max(axis=0) # across each columns what is the max number

array([63, 70, 65, 74, 76])

In [ ]:
d_arr.sum(axis=1)

array([182, 273, 227, 206])

In [ ]:
d_arr.sum(axis=0)

array([177, 153, 146, 233, 179])

In [ ]:
d_arr

array([[37, 28, 41, 33, 43],
       [63, 70, 25, 66, 49],
       [43, 19, 15, 74, 76],
       [34, 36, 65, 60, 11]])

In [ ]:
d_arr.sum(axis=1)

array([182, 273, 227, 206])

In [ ]:
d_arr.sum(axis=1)[2]

227

In [ ]:
# Indexing & Slicing

In [ ]:
# Indexing

In [ ]:
# 2 Golden Rule of Python 
# 1. When ever you are indexing in python, start from ZERO
# 2. When ever you are calculating a range, the last limit is exclusive
# range(4, 9) => 4,5,6,7,8 (not 9)

In [ ]:
list(range(4,9))

[4, 5, 6, 7, 8]

In [ ]:
# Syntax -> arr_name[row_number, col_number]
d_arr

array([[37, 28, 41, 33, 43],
       [63, 70, 25, 66, 49],
       [43, 19, 15, 74, 76],
       [34, 36, 65, 60, 11]])

In [ ]:
d_arr[1,2]

25

In [ ]:
d_arr[2,4]

76

In [ ]:
# Slicing 
# Syntax => arr_name[row_start_num:row_end_num, col_start_num:col_end_num]
d_arr[1:3, 1:3]

array([[70, 25],
       [19, 15]])

In [ ]:
d_arr

array([[37, 28, 41, 33, 43],
       [63, 70, 25, 66, 49],
       [43, 19, 15, 74, 76],
       [34, 36, 65, 60, 11]])

In [ ]:
d_arr[2:4, 2:5]

array([[15, 74, 76],
       [65, 60, 11]])

In [ ]:
d_arr[2:, 2:] # if you do not specify the end, numpy take the range to complete end

array([[15, 74, 76],
       [65, 60, 11]])

In [ ]:
d_arr[:3, :3]

array([[37, 28, 41],
       [63, 70, 25],
       [43, 19, 15]])

In [ ]:
# Neg Indexing 

# Positive Indexing
#.  0   1   2   3   4   5
# [29, 45, 36, 47, 63, 71]
# -6   -5  -4  -3  -2  -1
# Negative Indexing

In [ ]:
e_arr = np.random.randint(10, 90, (20))
e_arr

array([41, 48, 39, 22, 27, 46, 72, 61, 36, 25, 46, 13, 56, 86, 28, 50, 49,
       15, 15, 11])

In [ ]:
e_arr[8]

87

In [ ]:
e_arr[-2]

87

In [ ]:
e_arr[-4]

76

In [ ]:
# Stepping in Array

In [ ]:
e_arr

array([41, 48, 39, 22, 27, 46, 72, 61, 36, 25, 46, 13, 56, 86, 28, 50, 49,
       15, 15, 11])

In [ ]:
e_arr[3:6]

array([22, 27, 46])

In [ ]:
# start: stop: step 
e_arr[3:6:1]

array([22, 27, 46])

In [ ]:
e_arr[3:6:2]

array([22, 46])

In [ ]:
# start:stop: step 
# start 
# start + step 
# strat + step + step 
# start + step + step ... 

# continue with this untill you reach stop! 

In [ ]:
e_arr

array([41, 48, 39, 22, 27, 46, 72, 61, 36, 25, 46, 13, 56, 86, 28, 50, 49,
       15, 15, 11])

In [ ]:
e_arr[:6:3]
# 0, 3

array([41, 22])

In [ ]:
e_arr[2:7:4]
# 2, 6

array([39, 72])

In [ ]:
e_arr[2:5:7]

array([39])

In [ ]:
e_arr

array([41, 48, 39, 22, 27, 46, 72, 61, 36, 25, 46, 13, 56, 86, 28, 50, 49,
       15, 15, 11])

In [ ]:
e_arr[-5:-2:1]
# -5, -4, -3

array([50, 49, 15])

In [ ]:
e_arr[-3:-6:-1]
# -3, -4, -5

array([15, 49, 50])

In [ ]:
e_arr[5:2:-1]

array([46, 27, 22])

In [ ]:
# add something 